import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createClient } from "@/lib/supabase/server";
import { AuthButtons } from "@/components/auth-buttons";
import Image from "next/image";
import { Menu } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="sticky top-0 z-50 border-b bg-background/95 backdrop-blur">
          <div className="mx-auto flex h-14 items-center px-4" style={{ maxWidth: 960 }}>
            <div className="mr-6 flex items-center gap-2">
              <Image src="/logo.svg" alt="Logo" width={28} height={28} />
              <span className="font-semibold tracking-tight">urlist</span>
            </div>
            <nav className="hidden md:flex gap-6 text-sm">
              <a href="/" className="transition-colors hover:text-primary">Home</a>
              <a href="/features" className="text-muted-foreground transition-colors hover:text-primary">Features</a>
              <a href="/pricing" className="text-muted-foreground transition-colors hover:text-primary">Pricing</a>
              <a href="/about" className="text-muted-foreground transition-colors hover:text-primary">About</a>
            </nav>
            <div className="ml-auto flex items-center gap-2">
              <AuthButtons initialUserEmail={user?.email ?? null} />
              <Sheet>
                <SheetTrigger asChild>
                  <Button variant="ghost" size="icon" className="md:hidden" aria-label="Open menu">
                    <Menu className="h-5 w-5" />
                  </Button>
                </SheetTrigger>
                <SheetContent side="left" className="w-64">
                  <nav className="grid gap-4 py-4">
                    <a href="/" className="text-sm font-medium hover:text-primary">Home</a>
                    <a href="/features" className="text-sm font-medium hover:text-primary">Features</a>
                    <a href="/pricing" className="text-sm font-medium hover:text-primary">Pricing</a>
                    <a href="/about" className="text-sm font-medium hover:text-primary">About</a>
                    <AuthButtons initialUserEmail={user?.email ?? null} />
                  </nav>
                </SheetContent>
              </Sheet>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
